### ISSUE TITLE
Name-parser brings in name-parser-tests

### ISSUE THREAD

**Issue by timrobertson100** [gbif/name-parser#47]
Name-parser [has a compile time dependency on name-parser-tests](https://github.com/gbif/name-parser/blob/master/name-parser/pom.xml#L60) which means the `logback-test.xml` gets included in the e.g. the `checklistbank-nub-ws` which brings in insane amounts of logging at debug level.

It looks suspicious that this is depending on the tests jar in this way

**Comment by mdoering** [comment]
it's simply missing the test scope
