### ISSUE TITLE
Replace logback-test.xml with logback.xml

### ISSUE THREAD

**Issue by qifeng-bai** [gbif/name-parser#84]
logback-test.xml has a higher priority than logback.xml.  Using logback-test.xml prevents the other libs for load logback.xml

LA-pipelines report: 

WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [jar:file:/~/.m2/repository/**org/gbif/name-parser-api/3.1.11/name-parser-api-3.1.11-tests.jar!/logback-test.xml**]

Further investigation:

I was working on   org.gbif.pipelines:  2.10.0-SNAPSHOT version/branch - two weeks behind current dev branch

`org.gbif.pipelines`
`- org.gbif.gbif-parsers: 0.54`
`- org.gbif.name-parser-api - 3.1.11`

After I pull the dev branch,  the pipelines uses:

`- org.gbif.gbif-parsers: 0.57-snapshot`
`- org.gbif.name-parser-api - 3.7.1-snapshot`

This issue is solved

**Comment by timrobertson100** [comment]
Thanks QBai

Can you elaborate on where this causes issue please? The original design was presumably to allow a different logging configuration for the testing, which should only get into the *-tests.jar. 

Is it causing an issue in your test setup, or is this jar somehow getting onto your running app classpath?

Thanks

**Comment by mdoering** [comment]
Neither logback.xml nor logback-test.xml is included in the main resources. It is just for tests.
Can you explain the issue please?

**Comment by qifeng-bai** [comment]
In ALA pipelines, we cannot get our logback.xml loaded, unless we use logback-test.xml.  We found:

09:28:11,840 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [file:/~livingatlas/pipelines/target/classes/logback-test.xml]
09:28:11,840 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-test.xml] occurs at [jar:file:/~/.m2/repository/**org/gbif/name-parser-api/3.1.11/name-parser-api-3.1.11-tests.jar!/logback-test.xml]**
