### ISSUE TITLE
Salmonidae Jarocki or Schinz, 1822

### ISSUE THREAD

**Issue by mdoering** [gbif/name-parser#98]
Family `Salmonidae Jarocki or Schinz, 1822` parses wrongly and considers `or` a species epithet.
http://api.checklistbank.org/parser/name?q=Salmonidae%20Jarocki%20or%20Schinz,%201822

**Comment by timrobertson100** [comment]
Found in xcol impact report where a [lookup](http://backbonebuild-vh.gbif.org:9000/species/match2?usageKey=217387516) returns this (not it's OK in the name, but not in the classification):

```
{
  "synonym": false,
  "usage": {
    "key": 217387516,
    "name": "Salmonidae Jarocki or Schinz, 1822",
    "rank": "FAMILY"
  },
  "classification": [
    {
      "key": 214215335,
      "name": "Animalia",
      "rank": "KINGDOM"
    },
    {
      "key": 217148636,
      "name": "Chordata",
      "rank": "PHYLUM"
    },
    {
      "key": 217387493,
      "name": "Salmoniformes",
      "rank": "ORDER"
    },
    {
      "key": 217387516,
      "name": "Salmonidae or",
      "rank": "FAMILY"
    }
  ],
  "diagnostics": {
    "matchType": "EXACT",
    "confidence": 100,
    "status": "ACCEPTED",
    "lineage": [],
    "alternatives": [],
    "note": "All provided names were ignored since the usageKey was provided"
  }
}
```

**Comment by timrobertson100** [comment]
Can you please deploy it on http://backbonebuild-vh.gbif.org:9000/species/match2?usageKey=217387516 when it makes sense to (perhaps with the next release if that is soon)?

**Comment by timrobertson100** [comment]
I'm afraid [the lookup](http://backbonebuild-vh.gbif.org:9000/species/match2?usageKey=217387516) still has:

```
{
"key": 217387516,
"name": "Salmonidae or",
"rank": "FAMILY"
}
```

**Comment by mdoering** [comment]
well, that is a data issue, not parser.
This would only be fixed when we had a new release with new data - and I would actually have to make sure we update/sync the source that contributed the family name.

I thoought the problem was in parsing the request data.
